//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DaneOsoby", Namespace="http://tempuri.org/")]
    public partial class DaneOsoby : object
    {
        
        private double WzrostField;
        
        private double MasaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Wzrost
        {
            get
            {
                return this.WzrostField;
            }
            set
            {
                this.WzrostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double Masa
        {
            get
            {
                return this.MasaField;
            }
            set
            {
                this.MasaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BMIDane", Namespace="http://tempuri.org/")]
    public partial class BMIDane : object
    {
        
        private double BMIField;
        
        private string OpisField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double BMI
        {
            get
            {
                return this.BMIField;
            }
            set
            {
                this.BMIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHealthService")]
    public interface IHealthService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHealthService/Informacje", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.InformacjeResponse> InformacjeAsync(ServiceReference1.InformacjeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHealthService/ObliczBMIOsoby", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ObliczBMIOsobyResponse> ObliczBMIOsobyAsync(ServiceReference1.ObliczBMIOsobyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InformacjeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Informacje", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.InformacjeRequestBody Body;
        
        public InformacjeRequest()
        {
        }
        
        public InformacjeRequest(ServiceReference1.InformacjeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InformacjeRequestBody
    {
        
        public InformacjeRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InformacjeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InformacjeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.InformacjeResponseBody Body;
        
        public InformacjeResponse()
        {
        }
        
        public InformacjeResponse(ServiceReference1.InformacjeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InformacjeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InformacjeResult;
        
        public InformacjeResponseBody()
        {
        }
        
        public InformacjeResponseBody(string InformacjeResult)
        {
            this.InformacjeResult = InformacjeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObliczBMIOsobyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObliczBMIOsoby", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObliczBMIOsobyRequestBody Body;
        
        public ObliczBMIOsobyRequest()
        {
        }
        
        public ObliczBMIOsobyRequest(ServiceReference1.ObliczBMIOsobyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObliczBMIOsobyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.DaneOsoby daneOsoby;
        
        public ObliczBMIOsobyRequestBody()
        {
        }
        
        public ObliczBMIOsobyRequestBody(ServiceReference1.DaneOsoby daneOsoby)
        {
            this.daneOsoby = daneOsoby;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObliczBMIOsobyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObliczBMIOsobyResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObliczBMIOsobyResponseBody Body;
        
        public ObliczBMIOsobyResponse()
        {
        }
        
        public ObliczBMIOsobyResponse(ServiceReference1.ObliczBMIOsobyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObliczBMIOsobyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.BMIDane ObliczBMIOsobyResult;
        
        public ObliczBMIOsobyResponseBody()
        {
        }
        
        public ObliczBMIOsobyResponseBody(ServiceReference1.BMIDane ObliczBMIOsobyResult)
        {
            this.ObliczBMIOsobyResult = ObliczBMIOsobyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IHealthServiceChannel : ServiceReference1.IHealthService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class HealthServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IHealthService>, ServiceReference1.IHealthService
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HealthServiceClient() : 
                base(HealthServiceClient.GetDefaultBinding(), HealthServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IHealthService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HealthServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(HealthServiceClient.GetBindingForEndpoint(endpointConfiguration), HealthServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HealthServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HealthServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HealthServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HealthServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HealthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.InformacjeResponse> ServiceReference1.IHealthService.InformacjeAsync(ServiceReference1.InformacjeRequest request)
        {
            return base.Channel.InformacjeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InformacjeResponse> InformacjeAsync()
        {
            ServiceReference1.InformacjeRequest inValue = new ServiceReference1.InformacjeRequest();
            inValue.Body = new ServiceReference1.InformacjeRequestBody();
            return ((ServiceReference1.IHealthService)(this)).InformacjeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ObliczBMIOsobyResponse> ServiceReference1.IHealthService.ObliczBMIOsobyAsync(ServiceReference1.ObliczBMIOsobyRequest request)
        {
            return base.Channel.ObliczBMIOsobyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ObliczBMIOsobyResponse> ObliczBMIOsobyAsync(ServiceReference1.DaneOsoby daneOsoby)
        {
            ServiceReference1.ObliczBMIOsobyRequest inValue = new ServiceReference1.ObliczBMIOsobyRequest();
            inValue.Body = new ServiceReference1.ObliczBMIOsobyRequestBody();
            inValue.Body.daneOsoby = daneOsoby;
            return ((ServiceReference1.IHealthService)(this)).ObliczBMIOsobyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHealthService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHealthService))
            {
                return new System.ServiceModel.EndpointAddress("https://healthwebservice.azurewebsites.net/Health.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HealthServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IHealthService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HealthServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IHealthService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IHealthService,
        }
    }
}
